// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckCredentials() {
  return window['go']['core']['App']['CheckCredentials']();
}

export function GenerateTerraform(arg1) {
  return window['go']['core']['App']['GenerateTerraform'](arg1);
}

export function GetConfiguration() {
  return window['go']['core']['App']['GetConfiguration']();
}

export function GetEC2Instances() {
  return window['go']['core']['App']['GetEC2Instances']();
}

export function GetECSClusters() {
  return window['go']['core']['App']['GetECSClusters']();
}

export function GetECSMetrics(arg1, arg2) {
  return window['go']['core']['App']['GetECSMetrics'](arg1, arg2);
}

export function GetElasticIPs() {
  return window['go']['core']['App']['GetElasticIPs']();
}

export function GetLambdaFunctions() {
  return window['go']['core']['App']['GetLambdaFunctions']();
}

export function GetLoadBalancers() {
  return window['go']['core']['App']['GetLoadBalancers']();
}

export function GetNATGateways() {
  return window['go']['core']['App']['GetNATGateways']();
}

export function GetRDSInstances() {
  return window['go']['core']['App']['GetRDSInstances']();
}

export function GetRouteTables() {
  return window['go']['core']['App']['GetRouteTables']();
}

export function GetS3Buckets() {
  return window['go']['core']['App']['GetS3Buckets']();
}

export function GetSecurityGroups() {
  return window['go']['core']['App']['GetSecurityGroups']();
}

export function GetSubnets() {
  return window['go']['core']['App']['GetSubnets']();
}

export function GetTargetGroups() {
  return window['go']['core']['App']['GetTargetGroups']();
}

export function GetVPCs() {
  return window['go']['core']['App']['GetVPCs']();
}

export function Logout() {
  return window['go']['core']['App']['Logout']();
}

export function SaveAWSCredentials(arg1, arg2, arg3) {
  return window['go']['core']['App']['SaveAWSCredentials'](arg1, arg2, arg3);
}

export function SaveTerraformFile(arg1) {
  return window['go']['core']['App']['SaveTerraformFile'](arg1);
}

export function TestAWSConnection(arg1, arg2, arg3) {
  return window['go']['core']['App']['TestAWSConnection'](arg1, arg2, arg3);
}

export function VerifyPermissions() {
  return window['go']['core']['App']['VerifyPermissions']();
}
