// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CheckCredentials():Promise<boolean>;

export function GenerateTerraform(arg1:string):Promise<string>;

export function GetConfiguration():Promise<models.ConfigurationInfo>;

export function GetEC2Instances():Promise<Array<models.EC2InstanceInfo>>;

export function GetECSClusters():Promise<Array<models.ECSClusterInfo>>;

export function GetElasticIPs():Promise<Array<models.ElasticIPInfo>>;

export function GetLambdaFunctions():Promise<Array<models.LambdaFunctionInfo>>;

export function GetLoadBalancers():Promise<Array<models.LoadBalancerInfo>>;

export function GetNATGateways():Promise<Array<models.NATGatewayInfo>>;

export function GetRDSInstances():Promise<Array<models.RDSInstanceInfo>>;

export function GetRouteTables():Promise<Array<models.RouteTableInfo>>;

export function GetS3Buckets():Promise<Array<models.S3BucketInfo>>;

export function GetSecurityGroups():Promise<Array<models.SecurityGroupInfo>>;

export function GetSubnets():Promise<Array<models.SubnetInfo>>;

export function GetTargetGroups():Promise<Array<models.TargetGroupInfo>>;

export function GetVPCs():Promise<Array<models.VPCInfo>>;

export function Logout():Promise<void>;

export function SaveAWSCredentials(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveTerraformFile(arg1:string):Promise<string>;

export function TestAWSConnection(arg1:string,arg2:string,arg3:string):Promise<void>;

export function VerifyPermissions():Promise<Array<models.PermissionStatus>>;
